projects:
  Codegen Project:
    schemaPath: newschema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
      - src/API.js
    extensions:
      amplify:
        codeGenTarget: flow
        generatedFileName: src/API.js
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
