projects:
  Codegen Project:
    schemaPath: oldschema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - API.swift
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        apiId: null
        frontend: ios
        maxDepth: 2
extensions:
  amplify:
    version: 3
